### ISSUE TITLE
accessible_hamburger

### ISSUE THREAD

**Issue by gigster99** [scottaohara/accessible_hamburger#1]
May I ask you a question about accessible_hamburger?

I am writing CSS for a hamburger menu that is valid for Google Accelerated Mobile Pages (AMP). Here is my JS Fiddle.
[https://jsfiddle.net/jaygray/eu3r5qdk/2/](url)

 AMP does not allow the CSS 'input' and 'label' elements. Therefore your earlier effort:
[http://www.scottohara.me/article/morph-button-updated.html](url)
won't work with Google AMP.

However, this version has promise:
[https://github.com/scottaohara/accessible_hamburger](url)
as it does not use those CSS elements.

As you can see in my JS Fiddle, I have not been able to trigger the links and open the URLs. Using 'accessible hamburger' I am able to. And my JS Fiddle is a valid AMP document.

Google AMP does not allow JavaScript (except the AMP JavaScript). So this declaration:
`<html amp lang="en" class="no-js">`

must be:
`<html amp lang="en">`

And there may be other small changes so that accessible_hamburger works correctly for AMP.

Would you be willing to help me modify my CSS-only hamburger menu approach based on accessible_hamburger? I can help you negotiate AMP (I have written AMP valid HTML and can short-cut your learning curve). You then could present an AMP-valid structure. In return, I would have a solution for my applications.

Let me know if you have the time and interest to do this.

/jay

**Comment by scottaohara** [comment]
Hey there,

So, the way I understand what you're asking me, is that you want to use this for the no-js solution, as a CSS only powered hamburger menu, because AMA doesn't allow you to write any additional JavaScript?

I mean.  Based on how I understand what you're asking.  To me the solution to your issue would be to update the CSS to replace all instances of the `.no-js` class with `html[amp]`

The CSS only solution loses a lot of the accessibility hooks, and is meant to be used as a means to provide _some_ similar functionality when JavaScript is not available.  But I just wanted to throw out that a CSS only solution (even my old morph menu article that you referenced), aren't meant to be a final solution, but only part of one, or in the case of the morph menu, to just showcase what could be done with CSS, but not necessarily meant as a recommendation to do so in a live production setting.

**Comment by gigster99** [comment]
Thanks for the ringback. AMP is the new kid-on-the-block and publishers, like my firm, are aligning our HTML content with the new requirements. Except for specific Google JS, all other JS is banned. Therefore, more control needs to move back to CSS-only. Clearly, some control is lost. So we need to re-compose our menus. Previously, we used bootstrap.js - but can't do that any more. Hence the interest in your CSS-only solution, and specifically the version that also does not use `input` and `label` (also banned in AMP).

So, my request was to generalize your CSS-only approach for AMP where the starting point might be the merger of my Fiddle JS and your accessible_hamburger. My hope was that you would adapt your hamburger to my Fiddle.

You might want to offer different configurations. One might float, as yours does now. Another might be fixed, together with a logo, in a nav bar.

The point being, the AMP market needs a general purpose solution and none currently exists. I've got most of the code but can't close the gap that you have - namely, triggering the links. But I'm not a good CSS programmer and would rather work with someone who is - like you - to package a versatile, working solution. I can point to partial solutions from which I've learned. But someone with better skills than mine needs to pull them together.

Wadda ya think?
